#https://dev.to/felipetofoli/github-actions-for-net-full-framework-build-and-test-299h
name: Build and Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore .\Mcv\Mcv.sln

      - name: Build Solution
        run: |
          msbuild.exe .\Mcv\Mcv.sln /p:platform="Any CPU" /p:configuration="Release"

      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: published_webapp
          path: .\Mcv\bin

      - name: Run Tests
        run: vstest.console.exe .\Mcv.Tests\bin\Release\Mcv.Tests.dll /EnableCodeCoverage

      - name: Upload Test Reports to Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests